<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="worklog.php"><img src="../assets/img/parazei-small.png" height="50px"></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav"
            aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="worklog.php">Zeit buchen</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="global-projects.php">Globale Projekte</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="connections.php">Verbindungen</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="settings.php">Einstellungen</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="logout.php">Logout</a>
            </li>
        </ul>
    </div>
</nav>